### ISSUE TITLE
Link to feature request instead of discussion in README.md

### ISSUE THREAD

**Issue by razem-io** [mirko/SonOTA#109]
Hi,

to get as many votes as possible, in order to be able to downgrade firmware, the README should link to the feature request -> http://support.iteadstudio.com/support/discussions/topics/11000017070

It currently links to the product discussion instead, which seems to be the wrong place to request a feature.

Thank you for this great tool. I hope it will work again soon with Sonoff Basic!

**Comment by sillyfrog** [comment]
Updated, cheers!
