### ISSUE TITLE
no firmware is downloaded . no SSID "FinalStage

### ISSUE THREAD

**Issue by NiekN** [mirko/SonOTA#110]
- Operating System: win10
- Python Version:  sonota.exe
- Sonoff model: S20

i turned off firewall and virusscanner

startup sonota.exe  as admin
filled in: 0, mySSID, password

then pres 2x 7sec teh butten (led fast blink mode)
SSID itead . is comming online. so logged in

sonoff is blinking different, but no firmware is donwloaded . no SSID "FinalStage is showing up 
am i doing something wrong ??
 
[debug_1519585468x.txt](https://github.com/mirko/SonOTA/files/1756607/debug_1519585468x.txt)

**Comment by sillyfrog** [comment]
That looks to be the same as #53 - See the home page for information on reporting this to ITEAD, and hopefully getting them to support downgrading firmware.
