### ISSUE TITLE
S31 never see final stage

### ISSUE THREAD

**Issue by mattlward** [mirko/SonOTA#111]
- Operating System: 
Windows 10
  Firewall off
  Sonota.exe fresh download running as admin

- Python Version: 
Included in the exe dl
[debug_1519948773.log](https://github.com/mirko/SonOTA/files/1773228/debug_1519948773.log)

- Sonoff model: 
S31 with stock 1.0.0 firmware
Please also drag and drop the generated `debug_########.log` file onto the issue so it is attached.

**Comment by sillyfrog** [comment]
Please see #58  (and the project home page) for more details. I would encourage you to contact ITEAD as well to help get them to sort this out.
Cheers.

**Comment by poldim** [comment]
Experiencing the same behavior.
