### ISSUE TITLE
Sonoff Pow Module, not able to upgrade to latest Tasmota version

### ISSUE THREAD

**Issue by tali1974** [mirko/SonOTA#118]
Hi.. Thanks for the script you have made. I was able to flash my POW over the air,
I have now Program Version | 5.9.1 installed. Now i wanted to upgrade to v5.12.0.

I go to "Firmware Upgrade" added this in the OTA Url
https://github.com/arendst/Sonoff-Tasmota/releases/download/v5.12.0/sonoff-minimal.bin
and 
https://github.com/arendst/Sonoff-Tasmota/releases/download/v5.12.0/sonoff.bin
but the box boot after some sec and come up with 5.9.1.. 

Any idea what iam doing wrong ?

**Comment by LEMD49** [comment]
same issue here w POW

**Comment by sillyfrog** [comment]
The firmware only supports upgrading via HTTP, see this page for more information: https://github.com/arendst/Sonoff-Tasmota/wiki/Upgrade
