### ISSUE TITLE
Flash an ESP8285 from 3rd party hardware

### ISSUE THREAD

**Issue by tagazok** [mirko/SonOTA#123]
I have a couple of [Alfawise WIFI Smart Plug](https://www.gearbest.com/power-strips/pp_1303143.html?wid=1433363) that have an ESP8285 chip. After some research, it seems like it is the same as in the Sonoff touch. It also has a DLX-S20 V1.5 if this info is useful.

I was then wondering if I could use SonOTA to flash my Alfawise plug?

**Comment by sillyfrog** [comment]
The principal may work, but it's very much written for the ITEAD protocol, so best bet is to give it a go once you know you can flash it via serial if it all goes bad.
