### ISSUE TITLE
Does not work 

### ISSUE THREAD

**Issue by Dome2075** [mirko/SonOTA#126]
Hi,

i can't flasch my Sonof RF Bridge with Sonota but i don't no why?
when starting flash process the window close..
![unbenannt](https://user-images.githubusercontent.com/37158961/39829366-7e1717de-53be-11e8-80c0-dfa82daa45a7.JPG)

what happened?

thanks for help

**Comment by imadeyoureedthis** [comment]
Same problem here. Tested with the exe as well as with the py file. Attached log is from the py file.
Tried with three Sonoff Basic (R2 V1.0 2017-10-11).

System: Win 7 64bit
Python: 3.5.2
Firewall completely off

[log.txt](https://github.com/mirko/SonOTA/files/2294096/log.txt)
