### ISSUE TITLE
Can not connect to FinalStage

### ISSUE THREAD

**Issue by boerreth** [mirko/SonOTA#129]
- Operating System: Windows 10
- Python Version: 
- Sonoff model: Pow
I use current sonota.exe. I upgrade Sonoff Pow to version 2.4. Everything works fine until i see networ "FinalStage". I try to connect, but was disconnected immidately, so the las ".bin" file is not loaded to sonff Pow. Same happens for two other Sonoff pow.
Any idea what I am doing wrong?

Please also drag and drop the generated `debug_########.log` file onto the issue so it is attached.
[debug_1526847265.log](https://github.com/mirko/SonOTA/files/2023849/debug_1526847265.log)

**Comment by reloxx13** [comment]
read wiki and close this!!!

![grafik](https://user-images.githubusercontent.com/14855001/42127530-b44bad88-7c9a-11e8-857b-1ca96c1f10e9.png)
