### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by spokkie2015** [mirko/SonOTA#13]
I'm receiving the following error:

Barends-MacBook-Pro:~ Barend$ sudo python sonota.py
  File "sonota.py", line 397
    print(".", end="", flush=True)
                  ^
SyntaxError: invalid syntax

When I try to run the script

**Comment by cputoaster** [comment]
This probably because you are not using python3 but python2

**Comment by spokkie2015** [comment]
Will update and try again, thank you.

**Comment by spokkie2015** [comment]
Php3 solved the issue, and I got the process going but seem to have bricked my basic, comment in 404 issue.
