### ISSUE TITLE
IP Address and sonoff name

### ISSUE THREAD

**Issue by ordimans** [mirko/SonOTA#132]
- Operating System: Windows
- Python Version: 2.7
- Sonoff model: POW

Hello

It's possible to fix the IP Address in Manual ? Because it seems the IP change sometimes for the same device in DHCP.
Or i must set the IP on my routeur by MAC address.

Another think,, the name is Hostname (%s-%04d). Can i set manual ? I try %s-RXTOTO

and doesn't work... it come back on (%s-%04d)

**Comment by sillyfrog** [comment]
It sounds like you have successfully installed things. Now Sonoff-Tasmota is installed, I would suggest reading the Wiki at https://github.com/arendst/Sonoff-Tasmota/ for further assistance.
