### ISSUE TITLE
esp-open-rtos

### ISSUE THREAD

**Issue by kiralikbeyin** [mirko/SonOTA#137]
https://github.com/SuperHouse/esp-open-rtos
OPEN RTOS IS NOT ARDUINO BASE

rboot.bin TO 0x0
blank_config.bin TO 0x1000 
0x2000 image

I dont think it is too hard for you please have a look at it.

https://github.com/mirko/SonOTA/issues/134
Anyway upload esp-open-rtos binary at Final stage?

terminal upload for esp-open-rtos

esptool.py -p /dev/cu.usbserial-A7012RPU --baud 115200 write_flash -fs 8m -fm dout -ff 40m \

0x0 /Users/x/Documents/x/sdk/esp-open-rtos/bootloader/firmware_prebuilt/rboot.bin 

0x1000 /Users/x/Documents/x/sdk/esp-open-rtos/bootloader/firmware_prebuilt/blank_config.bin 

0x2000 ./firmware/Sonoff_Basic.bin

**Comment by sillyfrog** [comment]
SonOTA is designed to replace the stock boot loader with the Arduino one. That said, if the image is compiled to run from ROM address 0x0, then it should be fine. A write up of how it works is here: https://github.com/sillyfrog/Espressif2Arduino

Looking at that esptool command suggests it should be possible if you can make it a single image with all of the firmware in a single file.

That said, until ITEAD make it possible to use this again with the current releases, in some shape or from, I'm not putting a lot of energy into it as it won't be of much use to anyone.
