### ISSUE TITLE
S26 Support

### ISSUE THREAD

**Issue by WEZANGO** [mirko/SonOTA#144]
Hi, I am planing to buy S26 model, it's a new version on S20. But does SonOTA is working with it? Does anyone tried?

**Comment by sillyfrog** [comment]
Given the changes ITEAD has been making, I think it's _very_ unlikely SonOTA will work unfortunately. :(

**Comment by Kuki77** [comment]
I've tried it with S26F (Firmware 1.8) ... and unfortunately it's not working.
