### ISSUE TITLE
Script Failed while connecting to ITEAD...

### ISSUE THREAD

**Issue by verkruemelt** [mirko/SonOTA#145]
- Operating System: Windows 10 V1803 (Build 17134.228)
- Python Version: 3.7
- Sonoff model: basic
- Sonoff firmware version: --
[debug.log](https://github.com/mirko/SonOTA/files/2342133/debug.log)

Script fails at connecting to ITEAD-WLAN. Happend on 2 new basics.

**Comment by sillyfrog** [comment]
If they are new Sonoff's, they'll likely have the issue outlined on the home page - current firmware no longer works with SonOTA unfortunately.
