### ISSUE TITLE
Trying to use SonOTA to flash Sonoff Slampher_R2 (v1.7.0)

### ISSUE THREAD

**Issue by GitHubxtsnl** [mirko/SonOTA#149]
- Operating System: MacOS 10.13.6
- Python Version: 3.6
- Sonoff model: Sonoff Slampher_R2
- Sonoff firmware version: 1.7.0

[debug_1537212180.log](https://github.com/mirko/SonOTA/files/2389997/debug_1537212180.log)

- I have read the README, and understand that SonOTA does not work with the latest Sonoff firmware: ??? which is the latest version? is the Slampher_R2 supported to be flashed? How can I downgrade, an to which version?

I'm new to this, just bought my first Sonoff to be used with openHAB, so trying to flash it to a usable FW, unfortunately without any luck so far.

it gets to stage2, but I do not see the "FinalStage" network appearing.

any thoughts?

**Comment by sillyfrog** [comment]
Please see the readme on the home page, specifically the large font: _It appears SonOTA does not work with devices running firmware version 1.x >= 1.6!_

Unfortunately it won't work until ITEAD provides a way to do custom firmware over the air.
