### ISSUE TITLE
Admin password? in web interface?

### ISSUE THREAD

**Issue by alexmuntean** [mirko/SonOTA#150]
- Operating System: mac os
- Python Version: python 3
- Sonoff model: sonoff t1
- Sonoff firmware version: 2>
- I have read the README, and understand that SonOTA does not work with the latest Sonoff firmware: 

SonOTA worked fine (flashed my t1 2 weeks ago). the problem is that after a power surge nothing worked (hardware and it didn't connect to wifi). so.. I held down the first button and it worked.. it is now reset. It's connecting to wifi but when I try to access it I get a basic auth form.

I tried `admin` and no password but it isn't working.
I don't remember configuring `user_config.h` or anything... is there a default password?

How can I reset it? what can I do?

Thanks in advance

**Comment by sillyfrog** [comment]
As Sonoff-Tasmota successfully was flashed on to it, I would check the wiki and other issues there to see if others have had a similar problem (and solutions): https://github.com/arendst/Sonoff-Tasmota/wiki
