### ISSUE TITLE
Why is WIFI_SSID needed?

### ISSUE THREAD

**Issue by wewa00** [mirko/SonOTA#157]
"--wifi-ssid WIFI_SSID
The ESSID of the WiFi network the device should eventually connect to."

I actually don't see any reason why the Sonoff device should need connect to the home WIFI.
Which eventuality is meant here?

**Comment by sillyfrog** [comment]
That's how the Sonoff downloads the new firmware, SonOTA tells the Sonoff "connect to this WiFi, and download updates from here" (where here is a web server running on your PC).

**Comment by wewa00** [comment]
Ok, I thought for that the ITEAD-* network is used.

Are the different files (image_user1-0x01000.bin, ...) downloaded using different networks?

**Comment by sillyfrog** [comment]
Check out the sections under https://github.com/mirko/SonOTA#update-steps - this outlines what each bit is doing, and further down some more details.
