### ISSUE TITLE
SonOTA no longer working on new Sonoff devices

### ISSUE THREAD

**Issue by jleroux61** [mirko/SonOTA#16]
I received my sonoff 4ch. It has firmware v2.01. I wanted to try the new OTA process but the device no longer broadcasts the ssid. This is kind of breaking this process. Do you believe there is a solution to overcome this or is the end of OTA programming?
Thanks

**Comment by mirko** [comment]
Provisioning the device with the ewlink app and use SonOTA with `--skip-prov` for skipping provisioning.
