### ISSUE TITLE
[New Smart G2 2.0.1]Successfull flash, help for template/model selection

### ISSUE THREAD

**Issue by FrancYescO** [mirko/SonOTA#168]
Successfully flashed this device and upgraded via OTA (http://thehackbox.org/tasmota/release/sonoff.bin) to 6.5.0
![image](https://user-images.githubusercontent.com/4574593/59230434-c0314b00-8bdd-11e9-85ea-d8f27af71860.png)
Bought from here (90-250V **no-**RF module):
https://www.aliexpress.com/item/220v-inching-selflock-interlock-smart-relay-switch-220v-wifi-module-RF433-app-control-wifi-interruptor-alexa/32933270623.html?spm=a2g0s.9042311.0.0.27424c4dbwVMH3

But actually i'm not able to configure the model/template, if i press the first button one of the relays wil start switching in a loop, the other 2 seems to do nothing... do you have a template 

PS. I've readed the "new device" wiki, but all GPIOS seems to reply random, after ~60s one of the 2 relays start ticking each second found no way to just turn off/on relays, just GPIO13 for the main led seems right

**Comment by FrancYescO** [comment]
This is the right template https://blakadder.github.io/templates/geekcreit_2ch.html
Be sure to read the ***note*** in that page.

**Comment by gnasser76** [comment]
hello i bought this. https://www.aliexpress.com/item/32996254506.html?spm=a2g0s.9042311.0.0.27424c4dBDIrzN

is there a tasmota firmware as well as template ?
