### ISSUE TITLE
Can device get bricked if something goes wrong?

### ISSUE THREAD

**Issue by dzek69** [mirko/SonOTA#179]
There is one important thing missing from README -- can device get bricked an unuseable if something goes wrong during flashing?

If yes - can it still be repaired with serial connection or it will be broken forever?

I think these are important question for potential users of this software.

Can you please reply and add those info to README?

**Comment by sillyfrog** [comment]
I have just updated the Readme - in short, flashing via serial should be able to fix it. In my personal experience however, it either works, or does not work, and rebooting the device restores the stock firmware.

**Comment by dzek69** [comment]
thanks
