### ISSUE TITLE
Backup original firmware

### ISSUE THREAD

**Issue by calcipher49** [mirko/SonOTA#27]
Hi all
Great job for SonOTA project.
Is it possible using SonOTA to backup original frimware before flashing it?

Thank you

**Comment by sillyfrog** [comment]
It is not - from my (quick) research, I have not found a way to back up and restore the full original firmware (including boot loader). Which of course for development has made things tricky as I only have one go to get it right for each device! If you do find a way (or any one), please post it here.

**Comment by sillyfrog** [comment]
I have put my comments and progress so far on #1, including how to back it up - please let me know if this works for you.
