### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by jebo01** [mirko/SonOTA#35]
I´m following the instructions here https://github.com/mirko/SonOTA and the first stage goes well. In the second stage i get the following error 
.2017-10-12 21:07:01,051 (WARNING) error on read: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2083)

I´m not at all an advance user but would be great if anyone could point me in the right direction.
Have upgrade sonoff to latest firmeware and working of a Mac.

**Comment by sillyfrog** [comment]
Sounds like it's the same as #31 - does doing the same as this work?

**Comment by gdgeist** [comment]
OS X default Python and Openssl cause the issue.

**Comment by jebo01** [comment]
Thanks, yes same problem as in #31. I'll try this later on today.

**Comment by ro-76** [comment]
I'm having the same problem. 

2017-10-21 22:03:43,877 (WARNING) error on read: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:1976)

I had installed python manually, so I went and installed via homebrew, but I still get the error.

**Comment by sillyfrog** [comment]
@ro-76 Can you please send the output of `/usr/bin/env python3 --version`, and how you are calling the script? I'm guessing it's still using the system python.

**Comment by jebo01** [comment]
@ro-76 I had the same thing, I ran `brew doctor` and found some issues, after fixing those it all worked for me.
