### ISSUE TITLE
OSX Install

### ISSUE THREAD

**Issue by rlust** [mirko/SonOTA#46]
- Operating System: OSX High Sierra
- Python Version: 3.5.2
- Sonoff model: Sonoff

Please also drag and drop the log file to the issue so it is attached.

Getting the following error setting up requirements:

    /usr/bin/clang -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -DNETIFACES_VERSION=0.10.6 -I/Library/Frameworks/Python.framework/Versions/3.5/include/python3.5m -c netifaces.c -o build/temp.macosx-10.6-intel-3.5/netifaces.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command '/usr/bin/clang' failed with exit status 1
    
    ----------------------------------------
Command "/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 -u -c "import setuptools, tokenize;__file__='/private/var/folders/nn/fmy5ryln6xn42nnkh0k_l7c80000gn/T/pip-build-4frne3vz/netifaces/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/nn/fmy5ryln6xn42nnkh0k_l7c80000gn/T/pip-ybwlu4i9-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /private/var/folders/nn/fmy5ryln6xn42nnkh0k_l7c80000gn/T/pip-build-4frne3vz/netifaces/

**Comment by sillyfrog** [comment]
That just looks like development tools are not installed. Normally Mac OS should prompt you to install them, then after they are installed you can re-run the command.

You should also be able to install them by running the following as well: `xcode-select --install`
