### ISSUE TITLE
Works with TH16 v2.0.4

### ISSUE THREAD

**Issue by ChrisRomp** [mirko/SonOTA#49]
Sorry I can't figure out how to update your wiki page for compatible models, but this worked for me to update a new Sonoff TH16 with firmware 2.0.4. Thanks. 😄

**Comment by sillyfrog** [comment]
Updated, cheers.

**Comment by mouth4war** [comment]
Pardon the OT,  I've got a couple of TH16s on the way and was wondering if they have the power consumption measurement feature. From what I've read online, the POW and TH16 are identical apart from the sensor support.
