### ISSUE TITLE
SONOF RF Bridge WiFi 433 MHz 

### ISSUE THREAD

**Issue by wfa001** [mirko/SonOTA#52]
- Operating System: Windows 10
- Python Version: 3.5.4
- Sonoff model: SONOFF RF Bridge WiFi 433 MHz 

While trying to flash the Sonoff RF Bridge Device the process will not start stage 2 - FinalStage never shows up. Has anyone already successfully tried to flash this type of device?

[debug_1510487306.log](https://github.com/mirko/SonOTA/files/1464584/debug_1510487306.log)

**Comment by sillyfrog** [comment]
Looking at that log, my first guess would be the firewall - it's very common an issue on Windows. If you completely disable it for doing this flashing, things are likely to work.

Good luck!

**Comment by wfa001** [comment]
with the given setup i successfully flashed a sonoff touch without any problems. Firewall is switched off. Maybe the rf bridge needs different handling?

**Comment by sillyfrog** [comment]
I would suggest getting the latest build (as there have been a few important changes). But for this error try running with `--legacy` (and if that does not work, try updating to the latest Sonoff release using the eWeLink app first).
