### ISSUE TITLE
FinalStage does not show up

### ISSUE THREAD

**Issue by whuiscool** [mirko/SonOTA#55]
- Operating System: 
MacOS 10.13.1

- Python Version: 
python3.5

- Sonoff model: 
Sonoff Basic

Please also drag and drop the log file to the issue so it is attached.
[issue.log](https://github.com/mirko/SonOTA/files/1467087/issue.log)

**Comment by sillyfrog** [comment]
That looks like it's not the latest Python for Mac. See #31 and the README https://github.com/mirko/SonOTA
