### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by mateusromanbr** [mirko/SonOTA#63]
- Operating System: windows 10
- Python Version: 3.6.3
- Sonoff model: Basic

Please also drag and drop the generated `debug_########.log` file onto the issue so it is attached.

C:\SonOTA>sonota.py
  File "C:\SonOTA\sonota.py", line 156
    print("  {}%   ".format(int(f.tell()*100/length)), end="\r", flush=True)
                                                          ^
SyntaxError: invalid syntax

what is that error ?

**Comment by sillyfrog** [comment]
I'm guessing it's running the wrong version of Python (v2). I would suggest running as per the README and see if you get the same thing.

Good luck.
