### ISSUE TITLE
Win 10 Error in Line 156

### ISSUE THREAD

**Issue by Schnullerbua** [mirko/SonOTA#71]
- Operating System:  Win 10 64 bit
- Python Version: 3.6.3
- Sonoff model: Sonoff Basic Firmware 1.5.0

 File "E:\sonOTA\sonota.py", line 156
    print("  {}%   ".format(int(f.tell()*100/length)), end="\r", flush=True)

no debug log found sorry :-(

**Comment by sillyfrog** [comment]
That looks like it's running with python 2. I would suggest running with an explicit python version, eg: `python36 sonota.py`
