### ISSUE TITLE
H801 led controller support feature request

### ISSUE THREAD

**Issue by mouth4war** [mirko/SonOTA#72]
Hi, I was wondering if it could be possible to support H801 devices like arilux lc0x. Tasmota supports these devices in addition to Sonoffs.

Ps. Thanks a ton for this highly useful tool. I've used it on 4 TH16s just fine. Have a POW coming in and hoping it goes well too.

**Comment by mirko** [comment]
Thanks for the positive feedback!
SonOTA was created as a result of reverse-engineering and reimplementing the upgrade protocol ITEAD Sonoff devices are using. To fulfill your request, this effort would need to be done for the original H801 firmware as well which at least I don't intend to do for various reasons. Pull requests are always welcome though :)
