### ISSUE TITLE
Firmware 1.6.0 - never gets to stage 3

### ISSUE THREAD

**Issue by tynor88** [mirko/SonOTA#77]
- Operating System: Windows 10
- Python Version: Python 3.4.2
- Sonoff model: Sonoff S20 (EU)

[debug_1513632652.log](https://github.com/mirko/SonOTA/files/1569535/debug_1513632652.log)

Is it a known bug, that the firmware version 1.6.0 will never attempt to download the image from the webserver?

> 2017-12-18 22:32:46,155: WARNING: 404 GET / (10.0.0.105) 0.00ms

I made this get call, from a mobilephone, just to make sure there were no Firewall issues.

**Comment by sillyfrog** [comment]
Unfortunately, yes, it looks like we can no longer MITM the SSL connection, see here for all the details #58.
