### ISSUE TITLE
Sonoff 1.6.0 Firmware

### ISSUE THREAD

**Issue by KoLSMS** [mirko/SonOTA#78]
- Operating System: Windows 10x64
- Python Version: 3.5.4
- Sonoff model: S20

Hello, i have read several information that SonOTA is not working with the new Sonoff Original Firmware 1.6.0

So my question: Will there be a workaround or not? I have all my Sonoff with the 1.6.0 Firmware :(

Thx for help and reply!

**Comment by sillyfrog** [comment]
Please see #58 for further details and status. Unfortunately it does not look likely at this stage, unless ITEAD comes to the party, for which I'm requesting some Up Votes to try and get it to their attention :)
