### ISSUE TITLE
FinalStage never disappear

### ISSUE THREAD

**Issue by cirolaferrara** [mirko/SonOTA#80]
- Operating System: Windows10 / Ubuntu 16 Desktop
- Python Version: Python 3.6.3
- Sonoff model: Touch US

[debug_1514501222.log](https://github.com/mirko/SonOTA/files/1592365/debug_1514501222.log)

Firewall disabled and wifi profile on private on Windows 10.
Same problem on Ubuntu.
I can connect to FinalStage SSID and i can get 192.168.4.2 as IP

**Comment by mjoetoe** [comment]
same problem :( can't install die image_arduino.bin file , please help

**Comment by cirolaferrara** [comment]
Fixed with serial connection
