### ISSUE TITLE
Firmware 1.1?

### ISSUE THREAD

**Issue by MACscr** [mirko/SonOTA#85]
- Operating System: OSX
- Python Version: 3.6
- Sonoff model: RF Bridge

Anyone seen this? Ewlink is reporting that my Sonoff RF Bridge is running 1.1.0 and that its the latest version. This doesnt seem close to 1.5.5 or 1.6. Any suggestions?

**Comment by sillyfrog** [comment]
Different hardware has some very different versions numbers, that do not appear to match up with anything across models. See the Wiki for tested configurations here: https://github.com/mirko/SonOTA/wiki

It's worth giving a go, as worst case you'll need to use serial anyway.

Good luck!
