### ISSUE TITLE
Different responding Alexa On/Off

### ISSUE THREAD

**Issue by McFisherman** [mirko/SonOTA#90]
- Operating System: windows 10
- Python Version: sonota.exe
- Sonoff model: Basic

Hallo,  the exe file works like a charm. Couldn't get Alexa to find Sonoff with Wemo but with Hue emulation it did instantly. There's only one strange thing: if I ask Alexa to turn on the Sonoff the switch reponses and turns on. But Alexa says "name" is not responding". When I ask to turn it off the switch turns off and Alexa says "OK" Trying to get it back on again the same thing happens. Any idea why?

Add: just flashed second Sonoff Basic with same behaviour

**Comment by sillyfrog** [comment]
It sounds like the flashing has gone through OK. It's now running Sonoff-Tasmota, I would suggest you go to that project and see if others have a similar issue: https://github.com/arendst/Sonoff-Tasmota
