### ISSUE TITLE
Stuck in FinalStage

### ISSUE THREAD

**Issue by me-lina** [mirko/SonOTA#93]
- Operating System: Windows 10
- Python Version: used the exe
- Sonoff model: Sonoff Switch

I wanted to flash my last Sonoff Switch (the normal one, without RF) and got distracted so while it was nearly complete, my firewall activated again in the background. Dammit! -.-
You can see it in the log. It didn't work anymore, so I decided to try to start it from the beginning, or reset the Sonoff (doesn't work anymore), or disconnect it from power for a while, but nothing worked.

Is it bricked now? Or can I rescue it? I can still connect to "Final stage, but it's doing nothing anymore (see second log)

Can I rescue it by flashing it over hardware?

Greetings

[debug_1515199086.log](https://github.com/mirko/SonOTA/files/1608352/debug_1515199086.log)

[debug_1515200420.log](https://github.com/mirko/SonOTA/files/1608356/debug_1515200420.log)

**Comment by caserio** [comment]
i did  the  same  any  luck?   to  star   from 0?

**Comment by erwill2** [comment]
Mine did something similar and I had to connect and flash manually. I thought my switch was broken. It was clicking like crazy and stopped thought it was bricked for good. Flashing it brought it back to life.

**Comment by sillyfrog** [comment]
If you run the script with `--no-prov`, it'll take you to the end of the process, once you join the FinalStage SSID it should then download it within a minute or two.

Good luck!
