### ISSUE TITLE
How to flash custom Tasmota

### ISSUE THREAD

**Issue by sebastianlorenzen** [mirko/SonOTA#94]
Hello Guys,

is there a posibility to flash a customer bin file with custom settings?
I have made serveral settings before I flash via wire. I now want to use the same file to flash via OTA.
How can I do this?

Plan to use a Windows 10 box

**Comment by reloxx13** [comment]
Read ReadMe, thats why its calles ReadMe

https://github.com/mirko/SonOTA#important-files

**Comment by sebastianlorenzen** [comment]
Oops, thanks. Reading it a second time and found the right section. Will try it out.
