### ISSUE TITLE
Sonoff Dual R2 

### ISSUE THREAD

**Issue by donoo** [mirko/SonOTA#95]
- Operating System: Windows 10 
- Python Version:  3.5.4
- Sonoff model: Sonoff Dual R2

Hi,

I have flashed Sonoff Dual R2 using SonOTA. Everything is working fine. But I m not able to find options for enabling physical button as documented here : https://github.com/arendst/Sonoff-Tasmota/wiki/Sonoff-Dual-and-Dual-R2.

 I can only see following options in Config Page:

![image](https://user-images.githubusercontent.com/32016319/34649303-83d07680-f3d2-11e7-9bb9-c3c90607500e.png)

Is there way to enable these options while using SonOTA

![image](https://user-images.githubusercontent.com/32016319/34649314-b16c99ca-f3d2-11e7-8f12-a28fc1c0f797.png)

Thanks in advance!

Please also drag and drop the generated `debug_########.log` file onto the issue so it is attached.

**Comment by AlessandroEmm** [comment]
Have you updated to the latest release of tasmota? i think you should be asking there...

**Comment by donoo** [comment]
Hi,
Yes, after updating to latest version 5.11.1 i can see all options.
Thanks for the reply!
