### ISSUE TITLE
Update Phyton First

### ISSUE THREAD

**Issue by thiagoarreguy** [mirko/SonOTA#96]
- Operating System: Mac OS X
- Python Version: 3.6.4
- Sonoff model: basic one channel

I have to install phyton from zero (download the version 3.6.4 to Mac OS X ) and before the sonota.py works i had to run this in command line: 

pip3 install --upgrade pip 

pip3 install httplib2 --upgrade 
pip3 install netifaces --upgrade 
pip3 install tornado --upgrade﻿

**Comment by mirko** [comment]
The requirements and its versions are (already) specified in `requirements.txt`
